# Generated by Django 4.1.7 on 2023-03-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='挖矿创建时间')),
                ('flag', models.BooleanField(default=False, verbose_name='是否执行过')),
            ],
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='age',
        ),
        migrations.AddField(
            model_name='user_info',
            name='coin_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='羚羊币余额'),
        ),
    ]
