# Generated by Django 4.1.7 on 2023-03-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_mining_rename_name_user_info_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.user_info'),
        ),
    ]
