# Generated by Django 4.1.7 on 2023-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_mining_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本次挖矿收益'),
        ),
    ]
